version: "3.8"

services:
  memo-backend:
    image: node
    command: sh -c "npm install && npm run start"
    working_dir: /memo-backend
    volumes:
      - ./:/memo-backend
    ports:
      - "3000:3000"
    environment:
      POSTGRES_URI: postgres://admin:password@postgres:5432/memo-backend
  postgres:
    build: ./postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_URL: postgres://admin:password@localhost:5432/memo-backend
      POSTGRES_DB: memo-backend
      POSTGRES_HOST: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data