version: "3.8"

services:
  memo-backend:
    image: node
    command: sh -c "npm install && npm run start"
    working_dir: /memo-backend
    volumes:
      - ./:/memo-backend
    ports:
      - "3000:3000"
    environment:
      POSTGRES_URI: postgres://root:root@postgres:5432/root
  postgres:
    build: ./postgres
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  # PostgreSQL pgAdmin panel accessible at http://localhost:16543/
  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "placeholder@example.com"
      PGADMIN_DEFAULT_PASSWORD: "fakepassword123!"
    ports:
      - "16543:80"
    depends_on:
      - postgres