name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        run: docker-compose up -d
      - name: Test1
        run: docker-compose ps
      - name: Test2
        run: docker run --network container:memo-backend_memo-backend_1 appropriate/curl -s --retry 10 --retry-connrefused http://localhost:3000/
     
