name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Tests:
    runs-on: ubuntu-latest # TODO change to not latest , for some version.
    strategy:
      matrix:
        node-version: [17.3.1]

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint
